### ISSUE TITLE
Possible Way to implement Flags into Form or Twig

### ISSUE THREAD

**Issue by Hanmac** [odolbeau/phone-number-bundle#105]
I don't know if it would work that easy, but would it be possible to add country flags into the Form?

while searching for phone number features i found this: https://intl-tel-input.com/

might that be able to work with this Symfony Bundle?

**Comment by Nek-** [comment]
Hello, yes it could work. Many implementations can be done here. I'm not aware of the best practice in including frontend dependencies with Symfony Bundle, but it's definitely possible to do something and that would be super great.

However, there's some work to do here to end up with something cool. Feel free to suggest ways to implement it or purpose a pull request!

**Comment by Hanmac** [comment]
For Form Fields i found this:
https://symfony.com/doc/current/EasyAdminBundle/fields/CountryField.html

i did experiment with Standard Symfony Forms, and pure html forms doesn't support it, so the form theme needs something like jquery ui to replace the Select

**Comment by Nek-** [comment]
It would be really nice to have something working without jQuery.

**Comment by Hanmac** [comment]
jquery was just an example, the first link probably works without it

i just mean that it wouldn't be able to work with HTML alone but needs some kind of Javascript

because the `<option>` doesn't allow any kind of html inside the label

**Comment by Nek-** [comment]
Yes, you're absolutely right. Feel free to help us with it :) .

**Comment by maxhelias** [comment]
A PR is open #153, so I close the issue to centralize exchanges
