### ISSUE TITLE
Make constraint repeatable

### ISSUE THREAD

**Issue by AlexOstrovsky** [odolbeau/phone-number-bundle#146]
Would it be possible to make PhoneNumber attribute repeatable?

```php
#[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::IS_REPEATABLE)]
class PhoneNumber extends Constraint
{
}
```

**Comment by Nek-** [comment]
Hello, thank you for your suggestion. Can you provide a use case for this?

**Comment by AlexOstrovsky** [comment]
Hi @Nek- yes my use case is I have one class where I have $phoneNumber for multiple countries and I want to validate phoneNumber per country based on groups which represent countryIso

**Comment by Nek-** [comment]
@AlexOstrovsky can you provide some code sample please?

**Comment by AlexOstrovsky** [comment]
@Nek- 
`
#[PhoneNumber(format: PhoneNumberFormat::E164, type: [\Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::MOBILE], defaultRegion: CountryIso::LATVIA->value, message: 'GSM.INVALID', groups: [CountryIso::LATVIA->value])]
   
#[PhoneNumber(format: PhoneNumberFormat::E164, type: [\Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::MOBILE], defaultRegion: CountryIso::ESTONIA->value, message: 'GSM.INVALID', groups: [CountryIso::ESTONIA->value])]
   
#[PhoneNumber(format: PhoneNumberFormat::E164, type: [\Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::MOBILE], defaultRegion: CountryIso::DENMARK->value, message: 'GSM.INVALID', groups: [CountryIso::DENMARK->value])]
    
public ?PhoneNumberObject $gsm = null;
`

**Comment by AlexOstrovsky** [comment]
@Nek- any update on this?

**Comment by Nek-** [comment]
TBH didn't test it and I do not understand how there's not 2 failing no matter what. If the validator is called 3 times, then it will necessarily fail 2 times....

**Comment by AlexOstrovsky** [comment]
Because each repeated attribute has diffrent group.

**Comment by Nek-** [comment]
Oh ok, from what I understand, you are using groups as a workaround because there's no possibility to specify many countries in the constraints, or am I missing something?

**Comment by AlexOstrovsky** [comment]
My use case is like this: I have one API endpoint lets call it /api/formSubmit. This API endpoint is universal for all countries. But not all countries have all fields on frontend and phone number validation is diffreent per country. So I am using the groups (which represent country) to define what constraints should be validated in which country.

**Comment by AlexOstrovsky** [comment]
@Nek- so whats the conclusion? 😸

**Comment by Nek-** [comment]
@AlexOstrovsky I guess both should be done. You can open a PR for sure.

**Comment by AlexOstrovsky** [comment]
@Nek- I opened the PR: #167
