### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by julien-jourde** [odolbeau/phone-number-bundle#149]
Hello,

Any chance to have a new release with SF 6.3 deprecations solved ?

Have a nice day :)

**Comment by Nek-** [comment]
Definitely! Just to help me to have an idea of the work to be done, is master branch ok for you or are some things missing?

**Comment by julien-jourde** [comment]
For me, deprecations are fixed.

**Comment by alex-itech1** [comment]
> Definitely! Just to help me to have an idea of the work to be done, is master branch ok for you or are some things missing?

Hello.
Are you planning to make a new release from the master branch ? 

Because current tag is v3.9.1  (date 2023-01-16 11:06 UTC), it's too old, and it's without a fix for Symfony 6.3.
Thus it's impossible to use this package with version tag in composer in my project (Symfony 6.3). 

Thank you in advance

**Comment by maxhelias** [comment]
@alex-itech1 I'm surprised, what are the BC in v3.9.1 ?

**Comment by alex-itech1** [comment]
@maxhelias I'm afraid I don't understand your question.

I'm telling that the last version v3.9.1 is not working in Symfony 6.3.

https://github.com/odolbeau/phone-number-bundle/compare/v3.9.1...master
Here we can see that v3.9.1 a little bit old and does not contain fixes for Symfony 6.3, thus I wonder to know if you could do a new fresh release with including the fix, please

**Comment by maxhelias** [comment]
So, There's nothing to block Symfony 6.3 from working. The fix concern only notice deprecation not breaking change.

FYI : https://github.com/odolbeau/phone-number-bundle/pull/150

**Comment by maxhelias** [comment]
v3.9.2 was release : https://github.com/odolbeau/phone-number-bundle/releases/tag/v3.9.2
