### ISSUE TITLE
The license needs to be clarified for the bundle

### ISSUE THREAD

**Issue by OskarStark** [odolbeau/phone-number-bundle#15]
See https://github.com/odolbeau/phone-number-bundle/pull/14/files#r352033292

**Comment by maxhelias** [comment]
The original is here : https://github.com/odolbeau/phone-number-bundle/blob/master/Resources/meta/LICENSE, it might need to be adapted but I do not know in which way

**Comment by OskarStark** [comment]
* We should move it to the main folder to get github support
* I really don't know this license :D

btw. would be nice to be a maintainer on this bundle too!

**Comment by odolbeau** [comment]
> btw. would be nice to be a maintainer on this bundle too!
Welcome aboard! :)

**Comment by OskarStark** [comment]
> Welcome aboard! :)

Thanks 🚀
