### ISSUE TITLE
Request to make `symfony/framework-bundle` dependency optional

### ISSUE THREAD

**Issue by daniser** [odolbeau/phone-number-bundle#169]
I develop a package which uses `symfony/serializer` and `symfony/validator` components, but it is intended to be framework-agnostic.
This bundle (which is neat btw :) depends on heavy `symfony/framework-bundle` which is not needed when developing outside the framework. Right now I added it in `replace` section of my `composer.json`, but this solution is... suboptimal.

I suggest to move `symfony/framework-bundle` into dev-dependencies instead, plus into suggestions. What do you think?

**Comment by odolbeau** [comment]
Hi @daniser!
This package is a bundle which integrates [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) into Symfony.
It's tight with Symfony (including  `symfony/framework-bundle`) but it's on purpose.
If you dont' want this requirement, you should probably consider to use the library directly.
