### ISSUE TITLE
How to disable validator from form ?

### ISSUE THREAD

**Issue by fodger** [odolbeau/phone-number-bundle#177]
Hi,
I would like to disable validator on mobile phone field for a particular form.

How to do it ?

It doesn't work with FormEvents::PRE_SUBMIT (or PRE_SET_DATA), $form->isValid() uses always Validator\Constraints\PhoneNumber !

**Comment by maxhelias** [comment]
Hi,
You have many option :
- Remove the constraint on your entity field
- Or define this option on your form field : `'constraints' => [],` should work
- Or define a specific validation group on the constraint
