### ISSUE TITLE
Missing default region when deserializing

### ISSUE THREAD

**Issue by bizley** [odolbeau/phone-number-bundle#36]
I have tried to prepare test detecting wrong phone number when creating new user with API Platform and I have the following issue.

I'm sending

```json
{
      "phone": "123456789"
}
```

and this pops up

> Uncaught PHP Exception Symfony\Component\Serializer\Exception\UnexpectedValueException: "Missing or invalid default region." at /var/www/html/vendor/odolbeau/phone-number-bundle/src/Serializer/Normalizer/PhoneNumberNormalizer.php line 95

I have expected set default region to be passed but it's not happening and `PhoneNumberNormalizer` has default `ZZ`.

In my User entity I've got it like that:

```php
use Doctrine\ORM\Mapping as ORM;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

class User
{
    public const PHONE_DEFAULT_REGION = 'NO';

    /**
     * @ORM\Column(type="phone_number")
     * @Assert\NotNull()
     * @AssertPhoneNumber(defaultRegion=App\Entity\User::PHONE_DEFAULT_REGION)
     * @Groups({"user.read", "user.write"})
     */
    private ?PhoneNumber $phone = null;

    public function getPhone(): ?PhoneNumber
    {
        return $this->phone;
    }

    /**
     * @param PhoneNumber|string $phone
     * @throws NumberParseException
     */
    public function setPhone($phone): void
    {
        if (is_string($phone)) {
            $phone = PhoneNumberUtil::getInstance()->parse($phone, self::PHONE_DEFAULT_REGION);
        }

        $this->phone = $phone;
    }
}
```

Is there anything I'm doing wrong?

**Comment by odolbeau** [comment]
Hi @bizley!
The Serializer is initialized with `PhoneNumberUtil::UNKNOWN_REGION` by default so you have to send a number which include the country code (ie: +33601010101 for France).
If you don't want to have this country code inside the number, you can override the provided serializer service with the region your looking for.
It will be great if we could automatically override this serializer according to the configuration. Don't hesitate to propose a pull request if you want. :)

**Comment by bizley** [comment]
Oh, I was under impression that somehow setting the `defaultRegion` is enough ;) I'll look into it. Cheers

**Comment by bizley** [comment]
Yup. Service config:

```yml
Misd\PhoneNumberBundle\Serializer\Normalizer\PhoneNumberNormalizer:
        arguments:
            $region: 'NO'
```

works fine for my case.

**Comment by odolbeau** [comment]
Perfect! :ok_hand:
