### ISSUE TITLE
Form's view data is expected to be a "libphonenumber\PhoneNumber", but it is a "string".

### ISSUE THREAD

**Issue by someonewithpc** [odolbeau/phone-number-bundle#39]
I'm effectively defining the form as `$form->add('phone_number', PhoneNumberType::class, ['data' => $user->getPhoneNumber()])` with `LocalUser::getPhoneNumber(): ?libphonenumber\PhoneNumber`. The column is defined with type `'phone_number'`. Submitting the form works and the value is inserted in the database, after which the page shows the phone number with spaces between triplets, but if I go to that page again, I get the following error:

```
The form's view data is expected to be a "libphonenumber\PhoneNumber", but it is a "string". You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms "string" to an instance of "libphonenumber\PhoneNumber".
```

Obviously I don't want to unset the `data_class`, but I did try adding `'constraint' => [ new Constraints\PhoneNumber([]) ]'` like suggested in #32 

<sup>I'm not sure if using the constraint without passing something inside the array is valid, but I just want any phone number</sup>

**Comment by Nek-** [comment]
Hello,

Sorry to answer late but the validation works in any case. Are you sure your entity uses out custom type phone number? Because if you don't it will return a string which is indeed not supported by the form type.

**Comment by someonewithpc** [comment]
Positive. The error occurs after trying to view the page where the phone number is. Submitting it work fine, it shows up on the database and is reflected in the UI, formatted, but visiting the page again produces this error

**Comment by someonewithpc** [comment]
It could very well be an error on my side, but everything else seems to work. If you don't mind taking a look, the relevant code is:
 - https://notabug.org/someonewithpc/gnu-social/src/nightly/src/Controller/UserPanel.php#L98
 - https://notabug.org/someonewithpc/gnu-social/src/nightly/src/Core/Form.php#L86

**Comment by Nek-** [comment]
As I see you have a lot of custom code here. I can't find out the issue (spent like 10min on it), but it's most likely relative to your code (I'm using this bundle for many projects even with super custom code).

But if you really find a bug in our codebase I'd be glad to take a look at it.

If you find where it comes from, please post why and how so we can at least document this behavior.

Thanks (and sorry)

**Comment by someonewithpc** [comment]
I appreciate the effort and will try to find out why this happens.

I managed to dump the formbuilder and it looks fine (I guess I missed the _view data_ part of the error)

![image](https://user-images.githubusercontent.com/4998043/90322776-e6701a80-df47-11ea-928e-2a5cd22eb579.png)

**Comment by Nek-** [comment]
Something weird with your issue is that it involves the data_class which we never specify in our FormType.

Do you use it somewhere? Because if you specify explicitly the PhoneNumber class as data_class you may experiment this error because the configuration of the form type is by default using a [string in the form view](https://github.com/odolbeau/phone-number-bundle/blob/7f9530b521f4baaf55232f47a13b737b9343e895/src/Form/Type/PhoneNumberType.php#L122).

Use the following configuration to make it use the phone number:

```php
$formBuilder->add('phoneNumber', PhoneNumberType::class, [
    'widget' => PhoneNumberType:: WIDGET_COUNTRY_CHOICE
]);
```

**Comment by someonewithpc** [comment]
@Nek- That's weird, then, because I definitely don't specify it either

**Comment by someonewithpc** [comment]
Setting the `data_class` to null seems to actually work. I'm not sure where the error is coming from, though.

**Comment by Nek-** [comment]
Maybe you have a listener in your code that automatically adds this `data_class` if not set?

**Comment by Nek-** [comment]
I tested in a clean application with the last version of Symfony (5.1) just in case there were a change and it seems everything is working perfectly. I don't think your issue is related to our bundle.

**Comment by someonewithpc** [comment]
Ok, it's weird then. Thanks for the help, I'll close the issue

**Comment by kermitsxb** [comment]
Had similar issue today, found out it was my setter which cast the passed param as a string.

Found the solution on the original repo [here](https://github.com/misd-service-development/phone-number-bundle/issues/120#issuecomment-277221406)

**Comment by Nek-** [comment]
Yes indeed, if you have [non-strict type hinting](https://stackoverflow.com/questions/48723637/what-do-strict-types-do-in-php), the phone number is automatically converted to a string. To avoid that you need to have correct types in your getter return.

```
public function getPhoneNumber(): PhoneNumber // and not string.
{
    return $this->phoneNumber;
}
```

**Comment by kermitsxb** [comment]
Exactly, as I said my problem was on the setter of my class, which accepted a string type (copy/paste error) as parameter and then the validator had to validate a PhoneNumber::__toString() value which is not a valid value. Anyway I spent some stupid time on this problem which was not documented on this repo so I thought that it could help other people :)
