### ISSUE TITLE
PhoneNumberValidator instantiation issue

### ISSUE THREAD

**Issue by oojacoboo** [odolbeau/phone-number-bundle#44]
Getting the following error now since the last update.  What's changed?  This is from using the annotation assertion.

```
ArgumentCountError: Too few arguments to function Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator::__construct(), 0 passed
```

**Comment by odolbeau** [comment]
Hi @oojacoboo!

Some changes have been made by @BoShurik in order to improve the bundle configuration.
It's now possible to declare the default region you want to use for validation directly in the config.

However, those changes should now have broke your integration...

In order to allow us to debug, could please provide us the configuration you use for the bundle (if any), the output you get with the command `bin/console debug:config misd_phone_number` (if any) and the annotation you use?

Thanks for your help.

**Comment by oojacoboo** [comment]
We're not using the Symfony framework, only this component/bundle.  So, there isn't any debug information or a configuration for which I'm aware.

**Comment by maxhelias** [comment]
Why don't use giggsey/libphonenumber-for-php directly ?

**Comment by maxhelias** [comment]
So, in your case, you will need to add the dependencies manually

**Comment by oojacoboo** [comment]
@maxhelias Thanks.  I believe maybe we chose this over giggsey for the annotation class?  That is correct, yes?  This was something added by this lib?  Assuming we're using the annotation how do we go about manually injecting these dependencies?  It's sounds like, to me, we're going to be better off rolling our own annotation.  We rolled back to 3.1.1 for now which has resolved the issue, but obviously we're going to have to resolve this soon.  I'd imagine you've made changes in prep for PHP8?

**Comment by maxhelias** [comment]
So I have an another idea. Provide a default value in the construct on the validator. And when the value is null use the PhoneNumberUtil::getInstance.
PR will be welcome :)

**Comment by BoShurik** [comment]
If you use a dependency injection container you can fix this by using `ContainerConstraintValidatorFactory`
```php
use Psr\Container\ContainerInterface;
use Symfony\Component\Validator\ContainerConstraintValidatorFactory;
use Symfony\Component\Validator\Validation;

// Before

$validator = Validation::createValidator();

// After

/** @var ContainerInterface $container with \libphonenumber\PhoneNumberUtil service */

$builder = Validation::createValidatorBuilder();
$builder->setConstraintValidatorFactory(new ContainerConstraintValidatorFactory($container));
$validator = $builder->getValidator();
```

**Comment by maxhelias** [comment]
@oojacoboo Please look at #45, Can you confirm it's solve your issue ?

**Comment by oojacoboo** [comment]
@BoShurik @maxhelias #45 does resolve the issue.
