### ISSUE TITLE
Twig extension functions are deprecated

### ISSUE THREAD

**Issue by gnat42** [odolbeau/phone-number-bundle#47]
Hello,

   I've started using this bundle but noticed that one of the things that came over with the fork is that the twig functions phone_number_format and phone_number_is_type are marked as deprecated since 1.2. Are they being replaced? Is there a reason for the deprecation to stick? Just wondering if there's plans to do something there or not as its not really clear why there is a deprecation notice and no replacement.

**Comment by odolbeau** [comment]
Hi @gnat42 

Those twig functions were already deprecated & replaced by filters with the same name in the original repository.
In fact, I should have removed those functions in v2.0 but it looks like I forgot... :/

**Comment by gnat42** [comment]
Hello @odolbeau, Ah ok. It wasn't obvious what was supposed to replace them. Perhaps a code comment where the deprecation is to point to what should be used would be helpful...?

**Comment by Nek-** [comment]
Adding an `@deprecated see filters` comment could be great. Feel free to PR it :) .

**Comment by gnat42** [comment]
added a code comment in #50
