### ISSUE TITLE
Update from Misd fail (solution found)

### ISSUE THREAD

**Issue by webmasterMeyers** [odolbeau/phone-number-bundle#51]
When doing an upgrade from Misd bundle, I encountered a number of problems.

The readme for update from https://github.com/odolbeau/phone-number-bundle#update-from-misdphone-number-bundle is a little missleading/confusing.

I decided to update because I saw that you have merged some code I provided (never merged) to the original bundle.  But I had to update to version 3.2 not version 3.0, this took some time to figure out.  Maybe just ignorance on my part.

A second issue I had is one I beleive is related to Flex and recipes.  the line `Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],` had been removed from my `config/bundles.php` file, and thus I was getting missing services errors.

Reading the secion of the readme that says 

> If you're using Symfony Flex, your configuration config/packages/misd_phone_number.yaml have been removed. DO NOT REMOVE IT! If you're using a container paremeter or alias defined by misd/phone-number-bundle you can use "odolbeau/phone-number-bundle": "^2.0" until your project is cleaned.

This is only confusing and didn't help anything.  The recipe is still creating the `config/packages/misd_phone_number.yaml` file.

I guess my issue is solved, but maybe you need to look into flex recipes and what should be happening with this bundel.

**Comment by maxhelias** [comment]
Yes now the `config/packages/misd_phone_number.yaml` file is keeping. An update is necessary for this.
But the line `Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],` should not be remove. Do you have any information about this?

**Comment by webmasterMeyers** [comment]
looking back over my git history - I ran `composer remove misd/phone-number-bundle` which of cource removed `Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],` from the bundles file.

later running `composer require odolbeau/phone-number-bundle` might not have added back the missing line from the bundles file.

I had done a lot of removing and adding trying to trouble shoot a few issues with this.  I guess a quick test would discover if the line is being added.

**Comment by webmasterMeyers** [comment]
I just did a fresh symfony install and installing the bundle DOES add the the line to the bundles file.  So it is working corectly.  I must have messed that up myself, sorry for the false alarm.

However, why doe it only install 3.0? Why not the latest stable version?
