### ISSUE TITLE
Changelog should follow keep a changelog guidelines

### ISSUE THREAD

**Issue by Nek-** [odolbeau/phone-number-bundle#66]
Some tools parse the changelog (for example dependencies bot). It would be nice to have [a standard](https://keepachangelog.com/en/1.0.0/) format in the changelog.

I know most part of the time @odolbeau is the one that updates it, that's why I want approval before making a PR in that way :wink: .

**Comment by odolbeau** [comment]
This is the standard I use on some libraries. This is a great but the link on the version in the CHANGELOG is... boring! :sweat_smile: It regularly happens to me to forget it and / or to use an incorrect link in the release description (cause I add a link to the README).
This is obvisouly a small inconvenient.

Anyway, let's say I don't have any opinion on this subject.

**Comment by Nek-** [comment]
I guess we can just ignore the link to the version! (this is totally optional for most parsers)
