### ISSUE TITLE
add possibility for phone number by string

### ISSUE THREAD

**Issue by remdan** [odolbeau/phone-number-bundle#80]
If you have a string you can't use this "phone_number_format" in frontend then you need a "PhoneNumber" Object.

I miss a Twig-Filter in that bundle to get "PhoneNumber" Object or maybe the "phone_number_format" filter has to check that first.

`$phoneNumber = PhoneNumberUtil::getInstance()->parse($string);`

**Comment by almare** [comment]
Yeah, same problem here. Good idea.

**Comment by Nek-** [comment]
Hello, this twig extension already exists.

You can do the following:

```twig
{{ user.phoneNumber|phone_number_format }}
```
