### ISSUE TITLE
Symfony\Component\Intl not loaded error when use WIDGET_COUNTRY_CHOICE

### ISSUE THREAD

**Issue by NodokaMurmevent** [odolbeau/phone-number-bundle#81]
when i use the WIDGET_COUNTRY_CHOICE i have this error :
```
Attempted to load class "Intl" from namespace "Symfony\Component\Intl".
Did you forget a "use" statement for another namespace?
```

No error with WIDGET_SINGLE_TEXT i looked my php config an intl is enabled.
i use php 8.0.7

**Comment by maxhelias** [comment]
Yeah the symfony/form no longer has a dependency on symfony/intl. Just require `symfony/intl` in your project and that should fix your issue

**Comment by maxhelias** [comment]
BTW, I will make a new release that will correct this
