### ISSUE TITLE
"Can't get a way to read the property "phone_number" in class "...."

### ISSUE THREAD

**Issue by Mecanik** [odolbeau/phone-number-bundle#93]
Hi,

I followed the documentation, ensured property is inside the table, cleared cache; still the error persists.

<html>
<body>

CRITICAL06:13:38 | request | Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Can't get a way to read the property "phone_number" in class "...."." at ....\vendor\symfony\property-access\PropertyAccessor.php line 496{     "exception": {} }
-- | -- | --

</body>
</html>

I do not understand, what is the issue? I`m using Symfony 5.3.10.

**Comment by Mecanik** [comment]
I found the issue, your documentation is flawed. Please update the documentation to reflect the correct entity field name you specified:

```
use libphonenumber\PhoneNumberFormat;
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;
use Symfony\Component\Form\FormBuilderInterface;

public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('phoneNumber', PhoneNumberType::class, array('default_region' => 'GB', 'format' => PhoneNumberFormat::NATIONAL));
}
```

**Comment by maxhelias** [comment]
Hi,
This is an open source project, you are also allowed to correct the documentation.
And we would be happy to merge it.
